// src/components/utils/emoji/emoji-data.ts

import type { EmojiLocaleData } from './emoji-locale';

export interface ProcessedEmoji {
  native: string;
  skins: string[];
  id: string;
  name: string;
  keywords: string[];
  category: string;
}

export const CURATED_CALLOUT_EMOJIS: string[] = [
  '💡', '👉', '☝️', '✅', '⚠️', '🔑', '🔥', '📌', '✂️', '❓',
  '🚫', '⏰', '♻️', '🔒', '📖', '👣', '➡️', '📢', '🛠️', '⚙️',
];

// `pending` lets concurrent callers (many callouts rendering, prefetch racing
// open) share one import and one processing pass. Cleared on failure so a
// later call retries.
const grid: { data: ProcessedEmoji[] | null; pending: Promise<ProcessedEmoji[]> | null } = { data: null, pending: null };
const full: { done: boolean; pending: Promise<ProcessedEmoji[]> | null } = { done: false, pending: null };

/**
 * Every emoji in category order, with empty `keywords` until
 * `loadEmojiData()` fills them in place on this same array.
 */
export async function loadEmojiGrid(): Promise<ProcessedEmoji[]> {
  if (grid.data !== null) {
    return grid.data;
  }

  grid.pending ??= importEmojiGrid().finally(() => {
    grid.pending = null;
  });

  return grid.pending;
}

/**
 * The grid with English search keywords filled in. Resolves the same array
 * instance as `loadEmojiGrid()`.
 */
export async function loadEmojiData(): Promise<ProcessedEmoji[]> {
  if (full.done && grid.data !== null) {
    return grid.data;
  }

  full.pending ??= fillKeywords().finally(() => {
    full.pending = null;
  });

  return full.pending;
}

async function importEmojiGrid(): Promise<ProcessedEmoji[]> {
  // Generated by scripts/build-emoji-grid-data.mjs: `[{ id, emojis: [[id, name, ...skinNatives]] }]`.
  const { default: categories } = await import('./emoji-grid.json');

  const processed = categories.flatMap(category => category.emojis.map(([id, name, ...skins]): ProcessedEmoji => ({
    native: skins[0],
    skins,
    id,
    name,
    keywords: [],
    category: category.id,
  })));

  grid.data = processed;
  return processed;
}

async function fillKeywords(): Promise<ProcessedEmoji[]> {
  const [emojis, { default: keywords }] = await Promise.all([
    loadEmojiGrid(),
    import('./emoji-keywords.json'),
  ]);

  // The files are matched by position, so a stale one would mislabel emojis.
  if (keywords.length !== emojis.length) {
    throw new Error(`Emoji keywords (${keywords.length}) do not match the emoji grid (${emojis.length})`);
  }

  for (const [index, emoji] of emojis.entries()) {
    emoji.keywords = keywords[index];
  }

  full.done = true;
  return emojis;
}

export function searchEmojis(emojis: ProcessedEmoji[], query: string, localeData?: EmojiLocaleData | null): ProcessedEmoji[] {
  const lower = query.toLowerCase();
  return emojis.filter(emoji => {
    // English match; keywords stay empty until loadEmojiData() fills them
    if (emoji.name.toLowerCase().includes(lower) || emoji.keywords.some(k => k.includes(lower))) {
      return true;
    }

    // Translated match (when locale data is loaded)
    const entry = localeData?.[emoji.native];

    if (entry !== undefined) {
      return entry.n.toLowerCase().includes(lower) ||
        (entry.k !== undefined && entry.k.some(k => k.toLowerCase().includes(lower)));
    }

    return false;
  });
}

export function groupEmojisByCategory(emojis: ProcessedEmoji[]): Map<string, ProcessedEmoji[]> {
  const groups = new Map<string, ProcessedEmoji[]>();
  for (const emoji of emojis) {
    const group = groups.get(emoji.category) ?? [];
    group.push(emoji);
    groups.set(emoji.category, group);
  }
  return groups;
}
