plugins:
  # Tailwind CSS
  # https://tailwindcss.com/docs/installation/using-postcss
  tailwindcss: {}

  # Autoprefixer for vendor prefixes
  # https://github.com/postcss/autoprefixer
  autoprefixer: {}
