name: 'Setup Node.js and Dependencies'
description: 'Sets up Node.js and installs Yarn dependencies with caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'

outputs:
  cache-hit:
    description: 'Whether the Yarn cache was hit'
    value: ${{ steps.yarn-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Yarn dependencies
      id: yarn-cache
      uses: actions/cache@v4
      with:
        path: .yarn/cache
        key: yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable

    - name: Verify cache hit
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      shell: bash
      run: echo "::warning::Yarn cache miss, slower install expected"
