name: 'Setup Node.js and Dependencies'
description: 'Sets up Node.js and installs Yarn dependencies with caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'

outputs:
  cache-hit:
    description: 'Whether the Yarn cache was hit'
    value: ${{ steps.setup-node.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable

    - name: Install docs dependencies
      shell: bash
      run: |
        if [ -f docs/package.json ]; then
          cd docs && yarn install --immutable
        fi
