import type { SnapshotBlockStatics } from '../../../types';

const inlineTools = ['convertTo', 'marker', 'bold', 'italic', 'underline', 'clearFormat', 'link', 'strikethrough', 'inlineCode', 'equation', 'supSub'];
const tunes = ['delete', 'copyLink'];

// The live drift test pins these default English values and registration order.
export const BUILT_IN_BLOCK_STATICS: Readonly<Record<string, {
  title: string;
  statics: SnapshotBlockStatics;
  inlineTools: string[];
  tunes: string[];
}>> = {
  paragraph: {
    title: 'Text',
    statics: {
      toolbox: [
        { name: 'paragraph-0', title: 'Text', previewCaption: 'Just start writing with plain text' },
      ],
      richTextFields: ['text'],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: { export: 'text', import: 'text' },
      convertible: { export: true, import: true },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  header: {
    title: 'Heading 1',
    statics: {
      toolbox: [
        { name: 'header-1', title: 'Heading 1', data: { level: 1 }, previewCaption: 'Big section heading' },
        { name: 'header-2', title: 'Heading 2', data: { level: 2 }, previewCaption: 'Medium section heading' },
        { name: 'header-3', title: 'Heading 3', data: { level: 3 }, previewCaption: 'Small section heading' },
        { name: 'header-4', title: 'Heading 4', data: { level: 4 }, previewCaption: 'Subsection heading' },
        { name: 'header-5', title: 'Heading 5', data: { level: 5 }, previewCaption: 'Minor heading' },
        { name: 'header-6', title: 'Heading 6', data: { level: 6 }, previewCaption: 'Smallest heading' },
        { name: 'toggle-header-1', title: 'Toggle heading 1', data: { isToggleable: true, level: 1 }, previewCaption: 'A heading that hides the content under it' },
        { name: 'toggle-header-2', title: 'Toggle heading 2', data: { isToggleable: true, level: 2 }, previewCaption: 'A heading that hides the content under it' },
        { name: 'toggle-header-3', title: 'Toggle heading 3', data: { isToggleable: true, level: 3 }, previewCaption: 'A heading that hides the content under it' },
        { name: 'toggle-header-4', title: 'Toggle heading 4', data: { isToggleable: true, level: 4 }, previewCaption: 'A heading that hides the content under it' },
        { name: 'toggle-header-5', title: 'Toggle heading 5', data: { isToggleable: true, level: 5 }, previewCaption: 'A heading that hides the content under it' },
        { name: 'toggle-header-6', title: 'Toggle heading 6', data: { isToggleable: true, level: 6 }, previewCaption: 'A heading that hides the content under it' },
      ],
      richTextFields: ['text'],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: true,
      conversion: { export: 'text', import: 'text' },
      convertible: { export: true, import: true },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  list: {
    title: 'Bulleted list',
    statics: {
      toolbox: [
        { name: 'bulleted-list', title: 'Bulleted list', data: { style: 'unordered' }, previewCaption: 'Create a simple bulleted list' },
        { name: 'numbered-list', title: 'Numbered list', data: { style: 'ordered' }, previewCaption: 'Create a list with numbering' },
        { name: 'check-list', title: 'To-do list', data: { style: 'checklist' }, previewCaption: 'Track tasks with a to-do list' },
      ],
      richTextFields: ['text'],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: true, import: true },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  table: {
    title: 'Table',
    statics: {
      toolbox: [
        { name: 'table-0', title: 'Table', previewCaption: 'Add a table to your page' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: true,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: true,
      restrictedInTableCell: true,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  toggle: {
    title: 'Toggle list',
    statics: {
      toolbox: [
        { name: 'toggle', title: 'Toggle list', previewCaption: 'Toggles can hide and show content inside' },
      ],
      richTextFields: ['text'],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: { export: 'text', import: 'text' },
      convertible: { export: true, import: true },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  callout: {
    title: 'Callout',
    statics: {
      toolbox: [
        { name: 'callout', title: 'Callout', previewCaption: 'Make writing stand out' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: true, import: true },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  database: {
    title: 'Database',
    statics: {
      toolbox: [
        { name: 'database', title: 'Database', previewCaption: 'Organize pages in a table with properties' },
        { name: 'board', title: 'Board', previewCaption: 'Track work on a board of cards' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: true,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  'database-row': {
    title: 'Database-row',
    statics: {
      toolbox: [],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  divider: {
    title: 'Divider',
    statics: {
      toolbox: [
        { name: 'divider-0', title: 'Divider', previewCaption: 'Visually divide blocks' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  spacer: {
    title: 'Spacer',
    statics: {
      toolbox: [
        { name: 'spacer-0', title: 'Spacer', previewCaption: 'Add empty space between blocks' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  table_of_contents: {
    title: 'Table of contents',
    statics: {
      toolbox: [
        { name: 'table_of_contents-0', title: 'Table of contents', previewCaption: 'Show an outline of your page' },
      ],
      richTextFields: [],
      acceptsChildren: false,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  quote: {
    title: 'Quote',
    statics: {
      toolbox: [
        { name: 'quote-0', title: 'Quote', previewCaption: 'Capture a quote' },
      ],
      richTextFields: ['text'],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: { export: 'text', import: 'text' },
      convertible: { export: true, import: true },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  code: {
    title: 'Code',
    statics: {
      toolbox: [
        { name: 'code-0', title: 'Code', previewCaption: 'Capture a code snippet' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: { export: 'code', import: 'code' },
      convertible: { export: true, import: true },
      hasPrepareInsert: false,
    },
    inlineTools: [],
    tunes,
  },
  image: {
    title: 'Image',
    statics: {
      toolbox: [
        { name: 'image-0', title: 'Image', previewCaption: 'Upload an image or embed it with a link' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      assetKind: 'image',
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  file: {
    title: 'File',
    statics: {
      toolbox: [
        { name: 'file-0', title: 'File', previewCaption: 'Upload a file or link to one' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      assetKind: 'file',
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  audio: {
    title: 'Audio',
    statics: {
      toolbox: [
        { name: 'audio-0', title: 'Audio', previewCaption: 'Upload audio or embed it with a link' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      assetKind: 'audio',
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  video: {
    title: 'Video',
    statics: {
      toolbox: [
        { name: 'video-0', title: 'Video', previewCaption: 'Upload a video or embed it with a link' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      assetKind: 'video',
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  column_list: {
    title: '2 columns',
    statics: {
      toolbox: [
        { name: 'column_list-2', title: '2 columns', data: { columnCount: 2 }, previewCaption: 'Place blocks side by side in 2 columns' },
        { name: 'column_list-3', title: '3 columns', data: { columnCount: 3 }, previewCaption: 'Place blocks side by side in 3 columns' },
        { name: 'column_list-4', title: '4 columns', data: { columnCount: 4 }, previewCaption: 'Place blocks side by side in 4 columns' },
        { name: 'column_list-5', title: '5 columns', data: { columnCount: 5 }, previewCaption: 'Place blocks side by side in 5 columns' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: true,
      isLayout: true,
      deletesChildren: true,
      selfPlacesChildren: false,
      restrictedInTableCell: true,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  column: {
    title: 'Column',
    statics: {
      toolbox: [],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: true,
      deletesChildren: true,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  tabs: {
    title: 'Tabs',
    statics: {
      toolbox: [
        { name: 'tabs-0', title: 'Tabs', previewCaption: 'Switch between sections of content in tabs' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      childTools: { allow: ['tab'] },
      ownsChildren: true,
      isLayout: false,
      deletesChildren: true,
      selfPlacesChildren: false,
      restrictedInTableCell: true,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  tab: {
    title: 'Tab',
    statics: {
      toolbox: [],
      richTextFields: [],
      acceptsChildren: true,
      childTools: { deny: ['tabs'] },
      ownsChildren: false,
      isLayout: true,
      deletesChildren: true,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  embed: {
    title: 'Embed',
    statics: {
      toolbox: [
        { name: 'embed-0', title: 'Embed', previewCaption: 'Embed content from another site' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  bookmark: {
    title: 'Bookmark',
    statics: {
      toolbox: [
        { name: 'bookmark-0', title: 'Bookmark', previewCaption: 'Save a link as a visual bookmark' },
      ],
      richTextFields: [],
      acceptsChildren: true,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
  page: {
    title: 'Page',
    statics: {
      toolbox: [
        { name: 'page-0', title: 'Page', previewCaption: 'Embed a sub-page inside this page' },
      ],
      richTextFields: [],
      acceptsChildren: false,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: true, import: false },
      hasPrepareInsert: true,
    },
    inlineTools,
    tunes,
  },
  'page-link': {
    title: 'Page-link',
    statics: {
      toolbox: [],
      richTextFields: [],
      acceptsChildren: false,
      ownsChildren: false,
      isLayout: false,
      deletesChildren: false,
      selfPlacesChildren: false,
      restrictedInTableCell: false,
      conversion: {},
      convertible: { export: false, import: false },
      hasPrepareInsert: false,
    },
    inlineTools,
    tunes,
  },
};

export const BUILT_IN_INLINE_STATICS: Readonly<Record<string, {
  title: string;
  sanitizeTags: string[];
  shortcut?: string;
}>> = {
  convertTo: { title: '', sanitizeTags: [] },
  marker: { title: 'Color', sanitizeTags: ['mark'], shortcut: 'CMD+SHIFT+H' },
  bold: { title: 'Bold', sanitizeTags: ['strong', 'b'], shortcut: 'CMD+B' },
  italic: { title: 'Italic', sanitizeTags: ['i', 'em'], shortcut: 'CMD+I' },
  underline: { title: 'Underline', sanitizeTags: ['u'], shortcut: 'CMD+U' },
  clearFormat: { title: 'Clear formatting', sanitizeTags: [], shortcut: 'CMD+BACKSLASH' },
  link: { title: 'Link', sanitizeTags: ['a'], shortcut: 'CMD+K' },
  strikethrough: { title: 'Strikethrough', sanitizeTags: ['s', 'del', 'strike'], shortcut: 'CMD+SHIFT+S' },
  inlineCode: { title: 'Code', sanitizeTags: ['code'], shortcut: 'CMD+E' },
  equation: { title: 'Equation', sanitizeTags: ['span'], shortcut: 'CMD+SHIFT+E' },
  supSub: { title: 'Superscript & subscript', sanitizeTags: ['sup', 'sub'] },
};
