import {
  Audio,
  Bookmark,
  Callout,
  Code,
  Column,
  ColumnList,
  Database,
  DatabaseRow,
  Divider,
  Embed,
  File as FileTool,
  Header,
  Image as ImageTool,
  List,
  Page,
  Paragraph,
  Quote,
  Spacer,
  Table,
  TableOfContents,
  TabTool,
  TabsTool,
  Toggle,
  Video,
} from '../../../../src/tools';

// Page is host-registered rather than a default tool.
export const BLOCK_TOOL_CLASSES: Record<string, unknown> = {
  paragraph: Paragraph,
  header: Header,
  list: List,
  table: Table,
  toggle: Toggle,
  callout: Callout,
  database: Database,
  'database-row': DatabaseRow,
  divider: Divider,
  spacer: Spacer,
  table_of_contents: TableOfContents,
  quote: Quote,
  code: Code,
  image: ImageTool,
  file: FileTool,
  audio: Audio,
  video: Video,
  column_list: ColumnList,
  column: Column,
  tabs: TabsTool,
  tab: TabTool,
  embed: Embed,
  bookmark: Bookmark,
  page: Page,
};
