import type { Locale } from '../../i18n';

/**
 * One-sentence card text for the `/docs` hub, keyed by card id (the same id as
 * the link's `/docs/<id>`). The destination page keeps the full description.
 * The hub prerenders every card into HTML, so a full description here would
 * ship whole reference articles inside the index. `DocsHub.test.tsx` fails if
 * a card has no summary in either locale.
 */
export const DOCS_HUB_SUMMARIES: Record<Locale, Record<string, string>> = {
  en: {
    'quick-start': 'Get up and running with Blok in a few steps.',
    tutorial: 'Mount an editor, write some content, and save it as JSON you can load back.',
    concepts: 'The one idea behind Blok: every piece of content is a block.',
    'custom-block-tool': 'Build a callout block from scratch that renders, edits, and saves like a built-in one.',
    'tab-sync': 'Keep one document live across the tabs of one browser, with no server.',
    core: 'The main editor class that creates an instance and exposes every API namespace.',
    config: 'Every option you can pass to the Blok constructor, and which ones can change live.',
    'blocks-api': 'Create, delete, update, and reorder blocks in the editor.',
    'block-api': 'Work with a single block returned by the Blocks API.',
    'saver-api': 'Save and export editor content.',
    'view-state-api': 'Keep personal per-block state in this browser, outside the saved document.',
    'view-api': 'Render saved documents to HTML or plain text without loading an editor.',
    'caret-api': 'Move the cursor and control where it sits inside the editor.',
    'selection-api': 'Work with text selection inside the editor.',
    'marks-api': 'Apply and remove inline marks across a range when building formatting tools.',
    'styles-api': 'Use Blok class names and CSS custom properties to style tools and the editor.',
    'history-api': 'Control undo and redo for editor operations.',
    'toolbar-api': 'Open and close the block toolbar, its settings menu, and the toolbox.',
    'inline-toolbar-api': 'Control the inline formatting toolbar.',
    'ui-api': 'Reach Blok interface elements and their state.',
    'notifier-api': 'Show notifications to users, or plug in your own renderer.',
    'tooltip-api': 'Show tooltip hints on interface elements.',
    'theme-api': 'Read and switch the editor color theme at runtime.',
    'width-api': 'Switch the editor between narrow and full-width content.',
    'placeholder-api': 'Read and change the empty-editor placeholder without recreating the editor.',
    'tools-api': 'Inspect and manage the tools registered in the editor.',
    'uploader-api': 'Upload a file through the pipeline that owns its kind of asset.',
    'events-api': 'Subscribe to editor lifecycle events.',
    'listeners-api': 'Add and remove DOM event listeners with automatic cleanup.',
    'sanitizer-api': 'Clean HTML content to keep unsafe markup out of the editor.',
    'readonly-api': 'Turn editing on and off at runtime.',
    'i18n-api': 'Translate interface strings and switch the language at runtime.',
    'dev-override-seam': 'How the development override in every published entry works, and how to remove it.',
    'output-data': 'The data structure that saving the editor returns.',
    'block-data': 'The shape of each block in the saved blocks array.',
    'blok-editor': 'The ready-made editor component for React, Vue, and Angular.',
    'use-blocks': 'A live view of the block tree with methods to change it, for framework adapters.',
    'use-blok-ready': 'Know when the editors inside a part of the page are ready to use.',
    paragraph: 'The default text block with bold, italic, links, and color.',
    header: 'Headings from H1 to H6, each with a # shortcut.',
    list: 'Bulleted, numbered, and checklist items with unlimited nesting.',
    table: 'A table where every cell is its own small block editor.',
    toggle: 'A collapsible block that hides its child blocks behind an arrow.',
    callout: 'A highlighted box with an emoji icon and custom colors.',
    database: 'A database block with typed properties and board or list views.',
    'database-row': 'One row of a database, created and managed by its parent database block.',
    divider: 'A horizontal line that separates sections of content.',
    spacer: 'An adjustable vertical gap for lining up content.',
    table_of_contents: 'A live list of the page headings that jumps to each one.',
    quote: 'A block quote in two sizes, default and large.',
    code: 'A code block with syntax highlighting, a language picker, and a copy button.',
    image: 'Add an image by URL, by upload, or by pasting a file.',
    column_list: 'A layout block that places its children side by side in columns.',
    column: 'A single column inside a columns block.',
    tabs: 'A block that splits content into tabs, one open at a time.',
    tab: 'A single tab inside a tabs block, with a title and its own content.',
    embed: 'A live embed for YouTube, Figma, CodePen, and over 100 other services.',
    bookmark: 'A link preview card with title, description, and image.',
    page: 'A block that owns a nested page whose content lives in your app.',
    'page-link': 'A link to an existing page in your app that does not own it.',
    file: 'An attachment card with file name, size, and a download button.',
    audio: 'An audio player with a waveform scrubber and playback controls.',
    video: 'A video player with custom controls for playback and fullscreen.',
    bold: 'Make selected text bold with Cmd/Ctrl+B.',
    italic: 'Make selected text italic with Cmd/Ctrl+I.',
    link: 'Add, edit, or remove a link on selected text with Cmd/Ctrl+K.',
    marker: 'Color the selected text or its background.',
    underline: 'Underline selected text with Cmd/Ctrl+U.',
    strikethrough: 'Strike through selected text with Cmd/Ctrl+Shift+S.',
    inlineCode: 'Mark selected text as inline code with Cmd/Ctrl+E.',
    equation: 'Write inline math in LaTeX, rendered with KaTeX.',
    clearFormat: 'Remove inline formatting from selected text and keep links.',
    supSub: 'Turn selected text into superscript or subscript.',
  },
  ru: {
    'quick-start': 'Запустите Blok за несколько шагов.',
    tutorial: 'Подключите редактор, добавьте контент и сохраните его в JSON, который можно загрузить обратно.',
    concepts: 'Главная идея Blok: любой контент является блоком.',
    'custom-block-tool': 'Создайте с нуля блок-выноску, которая отрисовывается, редактируется и сохраняется как встроенный блок.',
    'tab-sync': 'Один документ остаётся актуальным во всех вкладках браузера, без сервера.',
    core: 'Главный класс редактора, который создаёт экземпляр и открывает все пространства имён API.',
    config: 'Все опции конструктора Blok и то, какие из них можно менять на лету.',
    'blocks-api': 'Создание, удаление, обновление и переупорядочивание блоков в редакторе.',
    'block-api': 'Работа с отдельным блоком, который возвращает API блоков.',
    'saver-api': 'Сохранение и экспорт содержимого редактора.',
    'view-state-api': 'Личное состояние блока в этом браузере, которое не попадает в сохранённый документ.',
    'view-api': 'Показ сохранённых документов в виде HTML или текста без загрузки редактора.',
    'caret-api': 'Управление позицией курсора внутри редактора.',
    'selection-api': 'Работа с выделением текста внутри редактора.',
    'marks-api': 'Применение и снятие строчных меток на диапазоне для инструментов форматирования.',
    'styles-api': 'Классы и CSS-переменные Blok для стилизации инструментов и редактора.',
    'history-api': 'Управление отменой и повтором операций редактора.',
    'toolbar-api': 'Открытие и закрытие панели инструментов блока, её меню настроек и тулбокса.',
    'inline-toolbar-api': 'Управление строчной панелью форматирования.',
    'ui-api': 'Доступ к элементам интерфейса Blok и их состоянию.',
    'notifier-api': 'Показ уведомлений пользователям или подключение собственной отрисовки.',
    'tooltip-api': 'Показ всплывающих подсказок на элементах интерфейса.',
    'theme-api': 'Чтение и смена цветовой темы редактора на лету.',
    'width-api': 'Переключение редактора между узким и полноширинным контентом.',
    'placeholder-api': 'Чтение и смена плейсхолдера пустого редактора без его пересоздания.',
    'tools-api': 'Просмотр и управление инструментами, зарегистрированными в редакторе.',
    'uploader-api': 'Загрузка файла через конвейер, который отвечает за его тип.',
    'events-api': 'Подписка на события жизненного цикла редактора.',
    'listeners-api': 'Добавление и снятие обработчиков DOM-событий с автоматической очисткой.',
    'sanitizer-api': 'Очистка HTML-контента от небезопасной разметки.',
    'readonly-api': 'Включение и выключение правки на лету.',
    'i18n-api': 'Перевод строк интерфейса и смена языка на лету.',
    'dev-override-seam': 'Как устроена подмена версии для разработки в каждой точке входа и как её убрать.',
    'output-data': 'Структура данных, которую возвращает сохранение редактора.',
    'block-data': 'Структура каждого блока в сохранённом массиве блоков.',
    'blok-editor': 'Готовый компонент редактора для React, Vue и Angular.',
    'use-blocks': 'Живое дерево блоков с методами для его изменения в адаптерах фреймворков.',
    'use-blok-ready': 'Узнайте, когда редакторы в части страницы готовы к работе.',
    paragraph: 'Текстовый блок по умолчанию с полужирным, курсивом, ссылками и цветом.',
    header: 'Заголовки от H1 до H6, у каждого уровня есть сочетание через #.',
    list: 'Маркированные, нумерованные списки и чек-листы с любой вложенностью.',
    table: 'Таблица, в которой каждая ячейка является отдельным редактором блоков.',
    toggle: 'Сворачиваемый блок, который прячет дочерние блоки за стрелкой.',
    callout: 'Выделенный блок с иконкой-эмодзи и настраиваемыми цветами.',
    database: 'Блок базы данных с типизированными свойствами и видами доски или списка.',
    'database-row': 'Одна строка базы данных, которую создаёт и ведёт родительский блок базы.',
    divider: 'Горизонтальная линия, которая разделяет части контента.',
    spacer: 'Регулируемый вертикальный отступ для выравнивания контента.',
    table_of_contents: 'Живой список заголовков страницы с переходом к каждому.',
    quote: 'Цитата двух размеров: обычного и крупного.',
    code: 'Блок кода с подсветкой синтаксиса, выбором языка и кнопкой копирования.',
    image: 'Изображение по URL, загрузкой или вставкой файла.',
    column_list: 'Блок раскладки, который ставит дочерние блоки колонками бок о бок.',
    column: 'Одна колонка внутри блока колонок.',
    tabs: 'Блок, который раскладывает содержимое по вкладкам, открытым по одной.',
    tab: 'Одна вкладка внутри блока вкладок, с названием и своим содержимым.',
    embed: 'Живое встраивание YouTube, Figma, CodePen и ещё более 100 сервисов.',
    bookmark: 'Карточка предпросмотра ссылки с заголовком, описанием и изображением.',
    page: 'Блок вложенной страницы, содержимое которой хранит ваше приложение.',
    'page-link': 'Ссылка на существующую страницу вашего приложения без владения ею.',
    file: 'Карточка вложения с именем файла, размером и кнопкой скачивания.',
    audio: 'Аудиоплеер с перемоткой по форме волны и кнопками управления.',
    video: 'Видеоплеер с собственными кнопками воспроизведения и полноэкранным режимом.',
    bold: 'Полужирное начертание выделенного текста по Cmd/Ctrl+B.',
    italic: 'Курсив для выделенного текста по Cmd/Ctrl+I.',
    link: 'Добавление, правка и удаление ссылки на выделенном тексте по Cmd/Ctrl+K.',
    marker: 'Цвет выделенного текста или его фона.',
    underline: 'Подчёркивание выделенного текста по Cmd/Ctrl+U.',
    strikethrough: 'Зачёркивание выделенного текста по Cmd/Ctrl+Shift+S.',
    inlineCode: 'Пометка выделенного текста как строчного кода по Cmd/Ctrl+E.',
    equation: 'Строчные формулы на LaTeX, которые отрисовывает KaTeX.',
    clearFormat: 'Снятие строчного форматирования с выделенного текста с сохранением ссылок.',
    supSub: 'Надстрочный или подстрочный индекс для выделенного текста.',
  },
};
