#!/usr/bin/env node
/**
 * Generates src/styles/fonts.css with base64-encoded @font-face declarations
 * for the four Notion-equivalent fonts bundled with Blok.
 *
 * Run: node scripts/generate-fonts.mjs
 * Run automatically as part of `yarn build` and `yarn build:test`.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

/**
 * Reads a woff2 file and returns a base64 data URI.
 */
function toDataUri(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`✗ Font file not found: ${filePath}`);
    console.error('  Run `yarn install` to restore @fontsource packages.');
    process.exit(1);
  }
  const bytes = fs.readFileSync(filePath);
  return `data:font/woff2;base64,${bytes.toString('base64')}`;
}

const fonts = [
  {
    family: 'Inter',
    style: 'normal',
    weight: '100 900',
    format: 'woff2-variations',
    display: 'swap',
    file: 'node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2',
  },
  {
    family: 'Source Serif 4',
    style: 'normal',
    weight: '200 900',
    format: 'woff2-variations',
    display: 'swap',
    file: 'node_modules/@fontsource-variable/source-serif-4/files/source-serif-4-latin-wght-normal.woff2',
  },
  {
    family: 'JetBrains Mono',
    style: 'normal',
    weight: '100 800',
    format: 'woff2-variations',
    display: 'block',
    file: 'node_modules/@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2',
  },
  {
    family: 'Permanent Marker',
    style: 'normal',
    weight: '400',
    format: 'woff2',
    display: 'block',
    file: 'node_modules/@fontsource/permanent-marker/files/permanent-marker-latin-400-normal.woff2',
  },
];

const blocks = fonts.map(({ family, style, weight, format, display, file }) => {
  const absPath = path.resolve(root, file);
  const dataUri = toDataUri(absPath);
  return [
    `@font-face {`,
    `  font-family: '${family}';`,
    `  font-style: ${style};`,
    `  font-display: ${display};`,
    `  font-weight: ${weight};`,
    `  src: url('${dataUri}') format('${format}');`,
    `}`,
  ].join('\n');
});

const output = [
  `/*`,
  ` * AUTO-GENERATED by scripts/generate-fonts.mjs`,
  ` * Do not edit manually. Run \`node scripts/generate-fonts.mjs\` to regenerate.`,
  ` */`,
  '',
  ...blocks,
  '',
].join('\n');

const outputPath = path.resolve(root, 'src/styles/fonts.css');
fs.writeFileSync(outputPath, output, 'utf8');
console.log(`✓ Generated ${outputPath} (${Math.round(output.length / 1024)} KB)`);
