name: Chromatic

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  chromatic:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps

      - name: Build Storybook
        run: yarn storybook:build

      - name: Run Chromatic
        uses: chromaui/action@69be7d88fc9479eedbe5b2861f847eb48f97cabc # latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
          exitZeroOnChanges: true
          autoAcceptChanges: main
